apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  db_username_devproject: emFvdWVsaQ== # Base64 encoded value of my username
  db_password_devproject: NDAyMzMyNjI= # Base64 encoded value of my password