apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service
spec:
  type: LoadBalancer
  selector:
    app: springbootapp-devopsproject
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086

---
apiVersion: v1
kind: Service
metadata:
  name: db-devopsproject
spec:
  selector:
    app: db-devopsproject
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
